#! /bin/sh

watch() {
  ls *.java | fgrep -v "Tests.java" | entr javac $(ls *.java | fgrep -v "Tests.java")
}

watch 2>&1 | grep -Fve "uses unchecked or unsafe operations" -e "Recompile with -Xlint:unchecked for details."
